language: ruby
rvm: 2.5

cache:
  bundler: true
  directories:
  - vendor/bundle
  - ".sass-cache"

install:
  - bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
  - mkdir -p bin tmp/kindlegen
  - curl http://kindlegen.s3.amazonaws.com/kindlegen_linux_2.6_i386_v2_9.tar.gz > tmp/kindlegen.tar.gz
  - tar zxvf tmp/kindlegen.tar.gz -C tmp/kindlegen
  - mv tmp/kindlegen/kindlegen bin/
before_script:
  - echo -n $TRAVIS_BUILD_NUMBER > _includes/travis_build_number.txt
script:
  - bundle exec rake build
after_success:
  - bin/deploy.sh

branches:
  except:
  - gh-pages

git:
  depth: 6

env:
  global:
    - secure: "WIpC5cBpQOC14SfT4kMh6kWTfPm280XJZEKAgftKPNlkQ3UN5mVSh6bwtS0O+mEZuJbNdCwfT1CMs/w1FE6VWHawKwZG9+38hH3iEKPENMRtBHHnYnDBKlcfnB67Hjy/5Feqw18L5PRTWbc4/uYENarFtvQrx1xKKRatlpzmExFI8OCVCmTf6V9EKHhhg/v7r9dyPC86h3BKUGHtZVhhe8975wyitz46UHEpYMuTY4ekI52TeFxvjGdTSkHzxhPaADgP4UHvwgOsxpcs4wsRLZIF3IOGVN74wAykIDBDyGj4Ou6MkPGwPRzk3cjB1JZ5zvmYfi4NDu3JQSHS9r3lJulzAtd5IVW+LRROyHc7U1UEyhfRyvGqUaD/bbMAK/jt1n6W0oUZO+Ar+HnEUPzaKnBdpKMja3Tc7yvC85QRAb0iDsIcNoopgRHolSAQTh6tAX/6R1IA81lj0JhAcqUsW+QfzWvPaDAoZFeHTscW6MS3izYbt67LFHc4bjsgEDcCfO8Z0vQqPzjNh6oTNWI1XyBJG3WXobP9VHTc5x3zH3oaEYIsv0VUj3f2TM/KNJ5AFQgKSl6YmWun5NyYMecYfAlhJVdoSo2GjA9vlFubzlpDksVi9sWAsuSDvcfrGtprFsMW0C3kErEm8O5Auh+xUXO0TrBO+W9z2YYwIjmGcKE="

deploy:
  provider: releases
  api_key:
    secure: yFesaHHSluwsCEoTrUmsoS5zYonKCvBBoGaH/bVKLjfZsW5K5dQM90Ipd/qQrBm2mZXTNUS8vG7pC2obeave9lNeaaIwc0s7pFdvPVJ8v2RAhGaaO53iVPiNG8mU4LOqOwzKkvMCesLzylkrslUqorur/AyKwdZbuH3L+7IeFdinAaDyxkiIkNn+ZwJNB/1DKagufVfuwU8urp166Zduo3B+Kod9utlneHu6fTkMrEFDI+end2PBIhygQohSkz9EBsu4kZUghLtwVPWz3Uk/RTb2Ry7vcSeA5ptIiTr2k3gTL/QDvVmAqov3pbqt+Qqh/H78PZ0RfjMZT80iJ+y1xSqkaAih23uTMw6mniQNx0g560pgJMkSgFv/twya/On4OtkvTkeLxw04j9vEhfn4hMTlUaAfZ1OaAhxAxhEOSAg0dGob26nH6Hfw8Vh4n5rqTvq/QFnX29mQECBm/qzMDeCl2OM9Tw0MkmH1nyY/X920jhhlVAgRIFz5FMyL15wJJisDNs/UWrmX+jrXy1mXlbHT1DTbJ8xGFkwRu8QxXgxQxwWzlyo6qIYj/v7VkX0UeCea5FvD+FSMighD/d9Pt7LAO4iKIoGMZJabXmuXDOHcGUeMrN2U/mqRVzaCSzHcYxZ1yvP7WNdpylZaOENiWy16JuT9mniV6oF5ByLhswg=
  file: _output/gotdict.mobi
  on:
    repo: wjdp/gotdict
    branch: master
    tags: true
