name: GOTDict

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.5
      - name: Install gems
        run: bundle install --jobs=3 --retry=3 --deployment
      - name: Install kindlegen
        run: |
          mkdir -p bin tmp/kindlegen
          curl https://f000.backblazeb2.com/file/wjdp-lib/kindlegen_linux_2.6_i386_v2_9.tar.gz > tmp/kindlegen.tar.gz
          tar zxvf tmp/kindlegen.tar.gz -C tmp/kindlegen
          mv tmp/kindlegen/kindlegen bin/
      - name: Store build number
        run: echo -n $(($GITHUB_RUN_NUMBER + 100)) > _includes/travis_build_number.txt
      - name: Build GOTDict
        run: bundle exec rake build
      - name: Deploy 🚀
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: _output/site # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
